<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Models\Customer.cs" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="PureDelivery.Shared.Contracts" Version="1.0.0" />
		<PackageReference Include="Serilog" Version="4.3.0" />
	</ItemGroup>
</Project>
